<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="UseCases\" />
    <None Remove="UseCases\Orders\" />
    <None Remove="UseCases\Orders\Interfaces\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="UseCases\" />
    <Folder Include="UseCases\Orders\" />
    <Folder Include="UseCases\Orders\Interfaces\" />
  </ItemGroup>
</Project>
